# Generated by Django 2.2.4 on 2020-01-31 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200130_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='link_address',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
