# Generated by Django 2.2.4 on 2020-01-31 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fixture_link_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='link_address',
            field=models.CharField(default=uuid.UUID('da6dbd0a-7567-4888-82ad-c4c66fc0fdd5'), max_length=50, unique=True),
        ),
    ]
