# Generated by Django 2.2.4 on 2020-01-31 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200131_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='link_address',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
